apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: k8s-application
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000

