apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: k8s-database
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 290848585164.dkr.ecr.us-east-1.amazonaws.com/clo835_app:mysqlv1.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "employees"
  imagePullSecrets:
  - name: ecr-secret

